// React Testing Library setup file for component tests
// This file is automatically loaded before each test via vitest.config.components.ts

import { cleanup } from '@testing-library/react';
import { afterEach, beforeAll, beforeEach } from 'vitest';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

// Extend Vitest's expect with jest-dom matchers
import '@testing-library/jest-dom/vitest';

// Initialize i18next for testing with inline resources
// This avoids the need to load translation files during tests
beforeAll(async () => {
  if (i18n.isInitialized) return;
  await i18n.use(initReactI18next).init({
    lng: 'de', // Default to German for tests
    fallbackLng: 'de',
    defaultNS: 'translation',
    ns: ['translation', 'categories'],

    // Inline resources for testing - complete set of translations
    resources: {
      de: {
        translation: {
          common: {
            save: 'Speichern',
            cancel: 'Abbrechen',
            delete: 'Löschen',
            rename: 'Umbenennen',
            ok: 'OK',
            close: 'Schließen',
            add: 'Hinzufügen',
            edit: 'Bearbeiten',
            remove: 'Entfernen',
            test: 'Testen',
            connect: 'Verbinden',
            connected: 'Verbunden',
            unknown: 'Unbekannt',
            error: 'Fehler',
            settings: 'Einstellungen',
            logout: 'Logout',
          },
          sidebar: {
            noAccount: 'Kein Konto',
            pleaseSetup: 'Bitte einrichten',
            neverSynced: 'Noch nie synchronisiert',
            manageAccounts: 'Konten verwalten',
            folders: 'Ordner',
            markings: 'Markierungen',
            starred: 'Markierte',
            smartMailbox: 'Intelligentes Postfach',
            createNewFolder: 'Neuen Ordner erstellen',
            aiCategories: 'KI Kategorien',
            other: 'Sonstiges',
            namePlaceholder: 'Name...',
            storage: 'Speicher',
            renameCategory: 'Kategorie umbenennen',
            renameCategoryPrompt: 'Geben Sie einen neuen Namen ein:',
            deleteCategory: 'Kategorie löschen',
            deleteCategoryConfirm: "Möchten Sie die Kategorie '{{category}}' wirklich löschen?",
            featureInDevelopment: 'Funktion in Entwicklung',
            iconSelectionComingSoon: 'Die Icon-Auswahl wird bald verfügbar sein!',
            changeIcon: 'Icon ändern',
            createNewCategory: 'Neue Kategorie erstellen',
            moveSelectedHere: 'Ausgewählte hierher verschieben ({{count}})',
          },
          settingsModal: {
            title: 'Einstellungen',
            tabs: {
              accounts: 'IMAP Konten',
              smartSort: 'Smart Sort',
              general: 'Allgemein',
            },
          },
          accountsTab: {
            connectedAccounts: 'Verbundene Konten',
            addAccount: 'Konto hinzufügen',
            connectNewAccount: 'Neues Konto verbinden',
            provider: 'Anbieter',
            providers: {
              gmx: 'GMX',
              webde: 'Web.de',
              gmail: 'Gmail',
              other: 'Andere',
            },
            displayName: 'Name (Anzeige)',
            displayNamePlaceholder: 'z.B. Arbeit',
            emailAddress: 'Email Adresse',
            emailPlaceholder: 'name@gmx.de',
            password: 'Passwort',
            passwordPlaceholder: 'Email Passwort',
            imapServer: 'IMAP Server',
            imapServerPlaceholder: 'imap.example.com',
            port: 'Port',
            testConnection: 'Verbindung testen',
            saveAndConnect: 'Speichern & Verbinden',
            removeAccount: 'Konto entfernen',
            connectionSuccess: 'Verbunden',
            connectionFailed: 'Verbindung fehlgeschlagen',
            testingError: 'Fehler beim Testen',
            webModeTestNotPossible: 'Web Mode: Test nicht möglich',
          },
          smartSortTab: {
            title: 'Smart Sort Konfiguration',
            description: 'Wähle die KI, die deine Emails sortiert.',
            llmProvider: 'LLM Anbieter',
            model: 'Modell',
            apiKey: 'API Key',
            apiKeyPlaceholder: 'sk-...',
            apiKeyPlaceholderOptional: 'Optional (verwendet Standard-Key)',
            geminiKeyInfo: 'Für Google Gemini ist bereits ein Demo-Key hinterlegt. Du kannst ihn überschreiben.',
            apiKeyInfo: 'Der API Key wird nur lokal im Browser für die Simulation verwendet.',
            saveSettings: 'Einstellungen speichern',
          },
          generalTab: {
            language: 'Sprache',
            selectLanguage: 'Sprache auswählen',
            dataManagement: 'Datenverwaltung',
            resetDatabase: 'Datenbank komplett zurücksetzen & neu starten',
            resetDatabaseTitle: 'Datenbank zurücksetzen',
            resetDatabaseConfirm: 'Achtung: Dies löscht alle gespeicherten Emails und Konten! Fortfahren?',
            resetButton: 'Zurücksetzen',
            resetError: 'Datenbank konnte nicht zurückgesetzt werden:',
            unknownError: 'Unbekannter Fehler',
          },
          topBar: {
            searchResults: 'Suchergebnisse',
            onlyUnsorted: 'Nur unsortierte',
            sortBy: 'Sortieren nach {{field}}',
            sortFields: {
              date: 'Datum',
              sender: 'Absender',
              subject: 'Betreff',
            },
            sortDirection: {
              ascending: 'Aufsteigend',
              descending: 'Absteigend',
            },
            fetchEmails: 'Emails abrufen',
          },
          searchBar: {
            placeholder: 'Suchen...',
            filters: 'Suchfilter',
            searchFields: 'Suchfelder',
            sender: 'Absender',
            subject: 'Betreff',
            body: 'Inhalt (Body)',
            logic: 'Logik',
            and: 'UND (Alle)',
            or: 'ODER',
            recentSearches: 'Letzte Suchen',
            searchOperators: 'Suchoperatoren',
            aiConvert: 'KI: In Suchoperatoren umwandeln',
            clearSearch: 'Suche löschen',
            operators: {
              from: 'Nach Absender filtern',
              subject: 'Im Betreff suchen',
              category: 'Nach Kategorie filtern',
              hasAttachment: 'E-Mails mit Anhängen',
              before: 'E-Mails vor Datum',
              after: 'E-Mails nach Datum',
            },
          },
          emailList: {
            noEmails: 'Keine Emails',
            emptyFolder: 'Dieser Ordner enthält noch keine Emails.',
            emails: 'Emails',
            loading: 'Lädt...',
            selectEmail: 'Wähle eine Email aus',
            markRead: 'Als gelesen markieren',
            markUnread: 'Als ungelesen markieren',
            delete: 'Löschen',
            flag: 'Markieren',
            unflag: 'Markierung entfernen',
            loadMore: 'Mehr laden...',
            dragCount_one: '{{count}} E-Mail',
            dragCount_other: '{{count}} E-Mails',
          },
          emailView: {
            noEmailSelected: 'Keine Email ausgewählt',
            selectEmail: 'Wähle eine Email aus der Liste aus, um den Inhalt anzuzeigen.',
            loadingContent: 'Lade Inhalt...',
            linkError: 'Link konnte nicht geöffnet werden',
            attachmentError: 'Anhang konnte nicht geöffnet werden',
            dismiss: 'Schließen',
            showText: 'Text',
            showHtml: 'HTML',
            blockedImages: '{{count}} externe Bilder blockiert',
            loadImages: 'Bilder laden',
            preparingView: 'Bereite Ansicht vor...',
            from: 'Von',
            to: 'An',
            cc: 'CC',
            bcc: 'BCC',
            date: 'Datum',
            subject: 'Betreff',
            attachments: 'Anhänge',
            reply: 'Antworten',
            forward: 'Weiterleiten',
            delete: 'Löschen',
            markAsRead: 'Als gelesen markieren',
            markAsUnread: 'Als ungelesen markieren',
            star: 'Markieren',
            unstar: 'Markierung entfernen',
            aiConfidence: 'KI-Konfidenz',
            aiAnalysis: 'Gemini Analyse',
          },
          categories: {
            inbox: 'Posteingang',
            sent: 'Gesendet',
            drafts: 'Entwürfe',
            trash: 'Papierkorb',
            spam: 'Spam',
            archive: 'Archiv',
            starred: 'Markiert',
            other: 'Sonstiges',
          },
          search: {
            placeholder: 'Suchen...',
            searchIn: 'Suchen in',
            all: 'Alle',
            subject: 'Betreff',
            from: 'Absender',
            to: 'Empfänger',
            body: 'Nachricht',
          },
          dialogs: {
            confirm: 'Bestätigen',
            cancel: 'Abbrechen',
            yes: 'Ja',
            no: 'Nein',
          },
          timeAgo: {
            justNow: 'Gerade eben',
            minuteAgo: 'Vor einer Minute',
            minutesAgo: 'Vor {{count}} Minuten',
            hourAgo: 'Vor einer Stunde',
            hoursAgo: 'Vor {{count}} Stunden',
            dayAgo: 'Vor einem Tag',
            daysAgo: 'Vor {{count}} Tagen',
            weekAgo: 'Vor einer Woche',
            weeksAgo: 'Vor {{count}} Wochen',
            monthAgo: 'Vor einem Monat',
            monthsAgo: 'Vor {{count}} Monaten',
            yearAgo: 'Vor einem Jahr',
            yearsAgo: 'Vor {{count}} Jahren',
          },
          batchActionBar: {
            selected: 'ausgewählt',
            selectedCount_one: '{{count}} ausgewählt',
            selectedCount_other: '{{count}} ausgewählt',
            markAsRead: 'Als gelesen',
            markAsUnread: 'Als ungelesen',
            flag: 'Markieren',
            unflag: 'Entmarkieren',
            smartSort: 'Smart Sortieren',
            tooltipApiKeyMissing: 'Bitte API Key in Einstellungen hinterlegen',
            tooltipSmartSort: 'Ausgewählte Mails mit AI sortieren',
          },
          simulationStart: {
            title: 'GMX AI Sorter',
            subtitle: 'Intelligenter E-Mail-Kategorisierungs-Prototyp',
            simulationModeTitle: 'Simulationsmodus:',
            simulationModeDescription:
              'Direkter IMAP-Zugriff ist im Browser nicht möglich. Diese App verwendet Gemini AI, um realistische E-Mail-Daten zu erzeugen und den KI-Sortieralgorithmus zu demonstrieren.',
            description:
              'Klicken Sie auf "Verbinden", um den Simulator zu starten. Gemini generiert Beispiel-Emails und sortiert diese automatisch in die richtigen Ordner.',
            connecting: 'Generiere Postfach...',
            connectButton: 'Mit Demo-Postfach verbinden',
            poweredBy: 'Bereitgestellt von Gemini 3 Flash Preview',
          },
          confirmDialog: {
            confirm: 'Bestätigen',
          },
          app: {
            emailsFlagged: '{{count}} Email(s) markiert',
            emailsMovedToCategory: '{{count}} Email(s) nach {{target}} verschoben',
            emailsMovedToFolder: '{{count}} Email(s) nach {{target}} verschoben',
            undoneAction: 'Rückgängig: {{description}}',
            loadDataError: 'Fehler beim Laden der Daten',
            loadAccountError: 'Fehler beim Laden des Kontos',
            addAccountError: 'Konto konnte nicht hinzugefügt werden. Prüfe die Daten.',
            newCategory: 'Neue Kategorie',
            newCategoryPrompt: 'Name der neuen Kategorie:',
            create: 'Erstellen',
            aiSortingProgress: 'AI sortiert Emails... ({{provider}})',
            undoButton: 'Rückgängig (Ctrl+Z)',
          },
          batch: {
            deleteTitle: 'Emails löschen',
            deleteConfirm: '{{count}} Emails wirklich löschen?',
            deleteError: 'Einige Emails konnten nicht gelöscht werden',
            updateError: 'Einige Emails konnten nicht aktualisiert werden',
            aiSettingsRequired: 'AI Settings erforderlich',
            configureApiKey: 'Bitte AI Settings (API Key) konfigurieren!',
            newFoldersSuggested: 'Neue Ordner vorgeschlagen',
            newFoldersMessage:
              "Die KI schlägt folgende neue Ordner vor:\n\n{{folders}}\n\nSollen diese angelegt werden?\n(Bei 'Abbrechen' werden die Mails in 'Sonstiges' verschoben)",
            createFolders: 'Anlegen',
            sortErrorTitle: 'Fehler beim Sortieren',
            sortErrorMessage: 'Ein Fehler ist beim Sortieren aufgetreten: {{error}}',
          },
          savedFilterDialog: {
            createTitle: 'Suchfilter speichern',
            editTitle: 'Suchfilter bearbeiten',
            nameLabel: 'Filtername',
            namePlaceholder: 'z.B. Amazon Rechnungen',
            queryLabel: 'Suchanfrage',
            queryPlaceholder: 'z.B. from:amazon category:Rechnungen',
            helpText: 'Verwenden Sie Suchoperatoren wie from:, subject:, category:, has:attachment, before:, after:',
            saveButton: 'Filter speichern',
            updateButton: 'Filter aktualisieren',
            errors: {
              nameRequired: 'Filtername ist erforderlich',
              queryRequired: 'Suchanfrage ist erforderlich',
            },
          },
        },
        categories: {
          categories: {
            INBOX: 'Posteingang',
            SENT: 'Gesendet',
            SPAM: 'Spam',
            TRASH: 'Papierkorb',
            INVOICE: 'Rechnungen',
            NEWSLETTER: 'Newsletter',
            PRIVATE: 'Privat',
            BUSINESS: 'Geschäftlich',
            CANCELLATION: 'Kündigungen',
            OTHER: 'Sonstiges',
          },
        },
      },
      en: {
        translation: {
          common: {
            save: 'Save',
            cancel: 'Cancel',
            delete: 'Delete',
            rename: 'Rename',
            ok: 'OK',
            close: 'Close',
            add: 'Add',
            edit: 'Edit',
            remove: 'Remove',
            test: 'Test',
            connect: 'Connect',
            connected: 'Connected',
            unknown: 'Unknown',
            error: 'Error',
            settings: 'Settings',
            logout: 'Logout',
          },
          sidebar: {
            noAccount: 'No Account',
            pleaseSetup: 'Please setup',
            neverSynced: 'Never synced',
            manageAccounts: 'Manage accounts',
            folders: 'Folders',
            markings: 'Markings',
            starred: 'Starred',
            smartMailbox: 'Smart Mailbox',
            createNewFolder: 'Create new folder',
            aiCategories: 'AI Categories',
            other: 'Other',
            namePlaceholder: 'Name...',
            storage: 'Storage',
            renameCategory: 'Rename category',
            renameCategoryPrompt: 'Enter a new name:',
            deleteCategory: 'Delete category',
            deleteCategoryConfirm: "Are you sure you want to delete the category '{{category}}'?",
            featureInDevelopment: 'Feature in development',
            iconSelectionComingSoon: 'Icon selection will be available soon!',
            changeIcon: 'Change icon',
            createNewCategory: 'Create new category',
            moveSelectedHere: 'Move selected here ({{count}})',
          },
          settingsModal: {
            title: 'Settings',
            tabs: {
              accounts: 'IMAP Accounts',
              smartSort: 'Smart Sort',
              general: 'General',
            },
          },
          accountsTab: {
            connectedAccounts: 'Connected Accounts',
            addAccount: 'Add Account',
            connectNewAccount: 'Connect new account',
            provider: 'Provider',
            providers: {
              gmx: 'GMX',
              webde: 'Web.de',
              gmail: 'Gmail',
              other: 'Other',
            },
            displayName: 'Display Name',
            displayNamePlaceholder: 'e.g. Work',
            emailAddress: 'Email Address',
            emailPlaceholder: 'name@gmx.de',
            password: 'Password',
            passwordPlaceholder: 'Email password',
            imapServer: 'IMAP Server',
            imapServerPlaceholder: 'imap.example.com',
            port: 'Port',
            testConnection: 'Test connection',
            saveAndConnect: 'Save & Connect',
            removeAccount: 'Remove account',
            connectionSuccess: 'Connected',
            connectionFailed: 'Connection failed',
            testingError: 'Error during testing',
            webModeTestNotPossible: 'Web Mode: Testing not possible',
          },
          smartSortTab: {
            title: 'Smart Sort Configuration',
            description: 'Choose the AI that sorts your emails.',
            llmProvider: 'LLM Provider',
            model: 'Model',
            apiKey: 'API Key',
            apiKeyPlaceholder: 'sk-...',
            apiKeyPlaceholderOptional: 'Optional (uses default key)',
            geminiKeyInfo: 'A demo key is already configured for Google Gemini. You can override it.',
            apiKeyInfo: 'The API key is only used locally in the browser for simulation.',
            saveSettings: 'Save settings',
          },
          generalTab: {
            language: 'Language',
            selectLanguage: 'Select language',
            dataManagement: 'Data Management',
            resetDatabase: 'Completely reset database & restart',
            resetDatabaseTitle: 'Reset database',
            resetDatabaseConfirm: 'Warning: This will delete all saved emails and accounts! Continue?',
            resetButton: 'Reset',
            resetError: 'Database could not be reset:',
            unknownError: 'Unknown error',
          },
          topBar: {
            searchResults: 'Search results',
            onlyUnsorted: 'Only unsorted',
            sortBy: 'Sort by {{field}}',
            sortFields: {
              date: 'Date',
              sender: 'Sender',
              subject: 'Subject',
            },
            sortDirection: {
              ascending: 'Ascending',
              descending: 'Descending',
            },
            fetchEmails: 'Fetch emails',
          },
          searchBar: {
            placeholder: 'Search...',
            filters: 'Search filters',
            searchFields: 'Search fields',
            sender: 'Sender',
            subject: 'Subject',
            body: 'Body',
            logic: 'Logic',
            and: 'AND (All)',
            or: 'OR',
            recentSearches: 'Recent Searches',
            searchOperators: 'Search Operators',
            aiConvert: 'AI: Convert to search operators',
            clearSearch: 'Clear search',
            operators: {
              from: 'Filter by sender email',
              subject: 'Search in subject line',
              category: 'Filter by smart category',
              hasAttachment: 'Emails with attachments',
              before: 'Emails before date',
              after: 'Emails after date',
            },
          },
          emailList: {
            noEmails: 'No emails',
            emptyFolder: "This folder doesn't contain any emails yet.",
            emails: 'Emails',
            loading: 'Loading...',
            selectEmail: 'Select an email',
            markRead: 'Mark as read',
            markUnread: 'Mark as unread',
            delete: 'Delete',
            flag: 'Flag',
            unflag: 'Remove flag',
            loadMore: 'Load more...',
            dragCount_one: '{{count}} email',
            dragCount_other: '{{count}} emails',
          },
          emailView: {
            noEmailSelected: 'No email selected',
            selectEmail: 'Select an email from the list to view its content.',
            loadingContent: 'Loading content...',
            linkError: 'Could not open link',
            attachmentError: 'Could not open attachment',
            dismiss: 'Dismiss',
            showText: 'Text',
            showHtml: 'HTML',
            blockedImages: '{{count}} external images blocked',
            loadImages: 'Load images',
            preparingView: 'Preparing view...',
            from: 'From',
            to: 'To',
            cc: 'CC',
            bcc: 'BCC',
            date: 'Date',
            subject: 'Subject',
            attachments: 'Attachments',
            reply: 'Reply',
            forward: 'Forward',
            delete: 'Delete',
            markAsRead: 'Mark as read',
            markAsUnread: 'Mark as unread',
            star: 'Star',
            unstar: 'Remove star',
            aiConfidence: 'AI Confidence',
            aiAnalysis: 'AI Analysis',
          },
          categories: {
            inbox: 'Inbox',
            sent: 'Sent',
            drafts: 'Drafts',
            trash: 'Trash',
            spam: 'Spam',
            archive: 'Archive',
            starred: 'Starred',
            other: 'Other',
          },
          search: {
            placeholder: 'Search...',
            searchIn: 'Search in',
            all: 'All',
            subject: 'Subject',
            from: 'Sender',
            to: 'Recipient',
            body: 'Message',
          },
          dialogs: {
            confirm: 'Confirm',
            cancel: 'Cancel',
            yes: 'Yes',
            no: 'No',
          },
          timeAgo: {
            justNow: 'Just now',
            minuteAgo: 'A minute ago',
            minutesAgo: '{{count}} minutes ago',
            hourAgo: 'An hour ago',
            hoursAgo: '{{count}} hours ago',
            dayAgo: 'A day ago',
            daysAgo: '{{count}} days ago',
            weekAgo: 'A week ago',
            weeksAgo: '{{count}} weeks ago',
            monthAgo: 'A month ago',
            monthsAgo: '{{count}} months ago',
            yearAgo: 'A year ago',
            yearsAgo: '{{count}} years ago',
          },
          batchActionBar: {
            selected: 'selected',
            selectedCount_one: '{{count}} selected',
            selectedCount_other: '{{count}} selected',
            markAsRead: 'Mark as read',
            markAsUnread: 'Mark as unread',
            flag: 'Flag',
            unflag: 'Unflag',
            smartSort: 'Smart Sort',
            tooltipApiKeyMissing: 'Please add API Key in settings',
            tooltipSmartSort: 'Sort selected emails with AI',
          },
          simulationStart: {
            title: 'GMX AI Sorter',
            subtitle: 'Intelligent Email Categorization Prototype',
            simulationModeTitle: 'Simulation Mode:',
            simulationModeDescription:
              'Direct IMAP access is not possible from a browser. This app uses Gemini AI to generate realistic email data and demonstrate how the AI sorting algorithm functions.',
            description:
              'Click "Connect" to start the simulator. Gemini will generate example emails and automatically sort them into the correct folders.',
            connecting: 'Generating mailbox...',
            connectButton: 'Connect with demo mailbox',
            poweredBy: 'Powered by Gemini 3 Flash Preview',
          },
          confirmDialog: {
            confirm: 'Confirm',
          },
          app: {
            emailsFlagged: '{{count}} email(s) flagged',
            emailsMovedToCategory: '{{count}} email(s) moved to {{target}}',
            emailsMovedToFolder: '{{count}} email(s) moved to {{target}}',
            undoneAction: 'Undone: {{description}}',
            loadDataError: 'Error loading data',
            loadAccountError: 'Error loading account',
            addAccountError: 'Account could not be added. Please check your data.',
            newCategory: 'New Category',
            newCategoryPrompt: 'Name of the new category:',
            create: 'Create',
            aiSortingProgress: 'AI sorting emails... ({{provider}})',
            undoButton: 'Undo (Ctrl+Z)',
          },
          batch: {
            deleteTitle: 'Delete emails',
            deleteConfirm: 'Really delete {{count}} emails?',
            deleteError: 'Some emails could not be deleted',
            updateError: 'Some emails could not be updated',
            aiSettingsRequired: 'AI Settings required',
            configureApiKey: 'Please configure AI Settings (API Key)!',
            newFoldersSuggested: 'New folders suggested',
            newFoldersMessage:
              "AI suggests the following new folders:\n\n{{folders}}\n\nShould these be created?\n(On 'Cancel', emails will be moved to 'Other')",
            createFolders: 'Create',
            sortErrorTitle: 'Error during sorting',
            sortErrorMessage: 'An error occurred during sorting: {{error}}',
          },
          savedFilterDialog: {
            createTitle: 'Save Search Filter',
            editTitle: 'Edit Search Filter',
            nameLabel: 'Filter Name',
            namePlaceholder: 'e.g. Amazon Invoices',
            queryLabel: 'Search Query',
            queryPlaceholder: 'e.g. from:amazon category:Invoices',
            helpText: 'Use search operators like from:, subject:, category:, has:attachment, before:, after:',
            saveButton: 'Save Filter',
            updateButton: 'Update Filter',
            errors: {
              nameRequired: 'Filter name is required',
              queryRequired: 'Search query is required',
            },
          },
        },
        categories: {
          categories: {
            INBOX: 'Inbox',
            SENT: 'Sent',
            SPAM: 'Spam',
            TRASH: 'Trash',
            INVOICE: 'Invoices',
            NEWSLETTER: 'Newsletter',
            PRIVATE: 'Private',
            BUSINESS: 'Business',
            CANCELLATION: 'Cancellations',
            OTHER: 'Other',
          },
        },
      },
    },

    // React-specific options
    react: {
      useSuspense: false, // Disable suspense for synchronous testing
    },

    // Interpolation options
    interpolation: {
      escapeValue: false, // React already escapes values
    },

    // Debug mode off for tests
    debug: false,
  });
});

// Ensure language is set to German before each test
beforeEach(async () => {
  await i18n.changeLanguage('de');
});

// Automatic cleanup after each test to prevent memory leaks
// and ensure test isolation
afterEach(() => {
  cleanup();
});
